# fly.toml app configuration file generated for nerves-hub on 2024-01-30T04:47:35+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
# Note: Since SSL termination is required on the app, [[services.ports]] should not include a `handlers` config.

app = 'spendra-nerves-hub-device'
primary_region = 'cdg'

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    force_https = false

  [[services.ports]]
    port = 443
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[env]
  NERVES_HUB_APP = "device"
  HOST = "spendra-nerves-hub-device.fly.dev"
  DEVICE_PORT = "8080"
  DATABASE_AUTO_MIGRATOR = "false" # Run migrations only from the web app to avoid conflicts
  DATABASE_SSL = "true"
  DATABASE_INET6 = "true"
  DATABASE_POOL_SIZE = "10"
  FIRMWARE_UPLOAD_BACKEND = "S3"
  S3_REGION="eu-central-1"
  FROM_EMAIL = "no-reply@spendra.swiss"
  MAILGUN_DOMAIN = "mg.spendra.swiss"
  RELEASE_COOKIE = "rbCViLyR6vLRdBmvN7sCDBb5loiWPYqSsPX_rmwHZD_VeK84em8WaA=="
  LOG_LEVEL = "debug"
